### PR TITLE
fix(resource_class): support optional mapping property from set_user_by_token

### LINKED ISSUE #174: getting an argument error when trying to use omniauth
ArgumentError in DeviseTokenAuth::OmniauthCallbacksController#redirect_callbacks

wrong number of arguments (1 for 0)

    # pull resource class from omniauth return
    def resource_class
      if omniauth_params
        omniauth_params['resource_class'].constantize
      end

Application Trace | Framework Trace | Full Trace
devise_token_auth (0.1.32.beta6) app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:105:in `resource_class'
devise_token_auth (0.1.32.beta6) app/controllers/devise_token_auth/concerns/set_user_by_token.rb:19:in `set_user_by_token'

it seems like the set_user_by_token method is calling resource_class with an argument but it is not supposed to take an argument.. 

it also looks like omniauth_callbacks_controller.rb is supposed to skip the set_user_by_token callback but it doesnt seem to be doing so... 

I also had this exact problem with 0.1.31... 

Any ideas?

### PR DESCRIPTION
**Pull request by booleanbetrayal**
Fixes #174

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
Let me know if you have any questions @lynndylanhurley !

**Comment by nbrustein** [comment]
:+1:

**Comment by piyushchauhan2011** [comment]
Please accept this request and release a stable version of this gem with newer tag. Its highly recommended.

**Comment by Cosmosz** [comment]
Solved my problem. :+1: Thanks

**Comment by piyushchauhan2011** [comment]
Thanks :+1:

**Pull request merged**
