### PR TITLE
removing old tokens when user changes passwords

### PR DESCRIPTION
**Pull request by paulosoares86**
Hey @booleanbetrayal. With this PR we can close issue https://github.com/lynndylanhurley/devise_token_auth/issues/318 with backwars compatibility, as you suggested. Please tell me if you have any other suggestions.

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
This looks great. Could you update the README Configuration section? Short of that, it looks good to go to me. Thanks @paulosoares86 !

**Comment by paulosoares86** [comment]
@booleanbetrayal, here it is. I've also changed a little typo. You're welcome!

**Comment by booleanbetrayal** [comment]
LGTM!

**Comment by paulosoares86** [comment]
LGTM! [2]. I'm looking for other issues to solve... hehehe. Btw, do you know why my commits are not been accounted ?

**Comment by booleanbetrayal** [comment]
probably your email address that you've got globally configured with git doesn't default to your github account and you didn't override it in the repo settings.

**Pull request merged**
