### PR TITLE
Update response param name

### PR DESCRIPTION
**Pull request by dhurba87**
I think token is reserved word in angularjs which causes problem in password reset

### CODE REVIEW

**Comment by MaicolBen** [comment]
@dhurba87 I couldn't find anything that token is reserved for angularjs, neither an issue in https://github.com/lynndylanhurley/ng-token-auth/. Can you point it me out? Because this is breaking change

**Comment by zachfeldman** [comment]
Hi there @dhurba87    ,

In an effort to cleanup this project and prioritize a bit, we're marking pull requests that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this pull request. Obviously feel free to re-open it at any time if it's the right time or this was done in error! If you do, please rebase it with the latest master and explain why it's still needed.

We really appreciate your contribution, we're just trying to make this project manageable again to move it forward.

Hope all is well.

**Comment by dhurba87** [comment]
I have used [this](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate) as a boilerplate for my app so maybe its the issue of boilerplate.

**Comment by MaicolBen** [comment]
I don't see any token there, can you put the error thrown here? This should have an issue opened first.

**Pull request closed without merging**
