### PR TITLE
Drop .ruby-version file

### PR DESCRIPTION
**Pull request by xymbol**
If needed, add a sample file or `required_ruby_version` entry.

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
I don't have strong opinions about this, but seeing as how most gemset managers can parse Gemfile / gemspecs I don't see any harm. One less thing to maintain.  =]

**Comment by xymbol** [comment]
@booleanbetrayal Agree but, it's a common practice to don't have it around.

**Comment by lynndylanhurley** [comment]
@xymbol - If we're going to merge this, can you please add the file to the `.gitignore` list as well?

**Comment by xymbol** [comment]
@lynndylanhurley Sorry about that, done.

**Pull request merged**
