### PR TITLE
Feature/i18n support

### PR DESCRIPTION
**Pull request by sebfie**
Use I18n for this gem. I finished the work started by @lukaselmer in #115

### CODE REVIEW

**Comment by sebfie** [comment]
I created a gist with french translation

**Comment by vic700208** [comment]
Thanks! I created a gist with spanish translation: https://gist.github.com/vic700208/bc86bfbb12f4f0720cd9

**Comment by lukaselmer** [comment]
Very nice, thanks!

**Comment by booleanbetrayal** [comment]
This is the most comprehensive PR for localization support atm, so I'm going to close the others. Will try to take a look at in the next couple of days. In the meantime, any reason not to bundle those gists in this PR? Would be nice to get some additional validation maybe.  =]

@sebfie - if it's not too inconvenient, could you squash those commits?

**Comment by sebfie** [comment]
How can I squash this commits? I do not know how to do that. @booleanbetrayal

**Comment by booleanbetrayal** [comment]
[here](https://asciinema.org/a/11269) is a decent example @sebfie  ... but basically you want to run `git rebase -i master`, mark the first commit you made as "r" (re-word), and all other commits as "f" (fixup). Save that in your editor, and it'll begin rebasing. You'll then get another editor popup for the re-word, where you can provide a comprehensive commit message. Once you're done, and you've verified everything looks good, you can push your changes with `git push -f` (forced push).

Let me know if you run into any issues though. I have a preference of keeping PR merges as single commits, but if it's too troublesome, we can merge as is.

**Comment by sebfie** [comment]
I did it.

**Comment by booleanbetrayal** [comment]
Thanks all! I'll add the other translations in a separate commit.

**Pull request merged**
