### PR TITLE
GET sign_in should direct people to use POST sign_in rather than raising exception

### PR DESCRIPTION
**Pull request by milesmatthias**
#190

### CODE REVIEW

**Comment by lynndylanhurley** [comment]
@milesmatthias - sorry for the delay - this looks good, I'll merge tonight!

**Comment by booleanbetrayal** [comment]
@milesmatthias - Can you rebase against master and resolve these conflicts? I'll merge once that happens. Thanks in advance!

**Comment by milesmatthias** [comment]
@booleanbetrayal done :smile:

**Comment by booleanbetrayal** [comment]
Thanks @milesmatthias !

**Comment by milesmatthias** [comment]
:+1:

**Pull request merged**
