### PR TITLE
concerns: set_user_by_token method collision possible fix

### PR DESCRIPTION
**Pull request by lolgear**
Anonymous function added as rescue to resource_class method collision. ( fix 'missing method' errors with cancan usage )

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
hey @lolgear - could you add a comment that also references #452 in that workaround block? just think this will be one of those situations where we come back awhile later and have no idea why this was done.  =]

**Comment by lolgear** [comment]
@booleanbetrayal, I want to write specs for tihs. It seems that `resource_class` doesn't work well for some situations.
The first try was: remove resource_class duplicate (failed): https://github.com/lynndylanhurley/devise_token_auth/pull/435

I commented why errors occurs.

**Comment by booleanbetrayal** [comment]
Specs would be great. Let me know once they're in and I'll take a look at this PR.

**Comment by booleanbetrayal** [comment]
Hey @lolgear - you want to see this one through?

**Comment by lolgear** [comment]
Hi, @booleanbetrayal - yes, I want

**Comment by lolgear** [comment]
@booleanbetrayal but it seems, that @rossshannon improve my PR and find another ( maybe better ) solution. ( look at issue #450 that was referenced earlier )

**Comment by jvalenciag** [comment]
+1

**Pull request closed without merging**
