### PR TITLE
RU translations

### PR DESCRIPTION
**Pull request by yivo**

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
Thanks @yivo - ironically enough, a couple of minutes ago I just pushed a fix to all the locales where the `message` entry was fixed to the proper `messages` entry. Could you amend your commit with the fix? Thanks!

**Comment by booleanbetrayal** [comment]
see also: b9e68cec6ed6f2f9842e39d8fd3a1e93cfac38a5

**Comment by yivo** [comment]
@booleanbetrayal, fixed!

**Comment by booleanbetrayal** [comment]
Awesome!

**Pull request merged**
