### PR TITLE
Added ukrainian locale

### PR DESCRIPTION
**Pull request by Dimkarodinz**

### CODE REVIEW

**Comment by zachfeldman** [comment]
Thanks for your contribution @Dimkarodinz . I translated a few of these to ensure you weren't insulting anyone (hehe). Looks good to me, I'm going to merge once the tests pass.

**Comment by zachfeldman** [comment]
@Dimkarodinz this appears to have broken the build

**Comment by Dimkarodinz** [comment]
@zachfeldman It was a typo, fixed

**Comment by zachfeldman** [comment]
Great, going to merge!

**Pull request merged**
