### PR TITLE
Fix invalid omniauth redirect

### PR DESCRIPTION
**Pull request by troggy**
Addresses issue #285

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
Thanks for this PR @troggy, but we shouldn't be using `File.join` since the separator isn't guaranteed to be the same across environments. Can you refactor to use vanilla string concatenation instead?

**Comment by c0mrade** [comment]
:+1:

**Comment by booleanbetrayal** [comment]
@c0mrade - between you and @troggy , whoever gets me a PR for this (without the `File.join` and preferably with a test) wins!  =]

**Comment by troggy** [comment]
Like this?

**Comment by c0mrade** [comment]
@booleanbetrayal is this good what troggy did?

**Comment by booleanbetrayal** [comment]
Thanks! Got lost in the shuffle of a cross-country move.  =]

**Pull request merged**
