### PR TITLE
Clean readme & move doc  

### LINKED ISSUE #75: Testing with rspec
Most tutorials out there for `devise_token_auth` talk about using **feature specs** to test authentication integration. This is great, of course, but it doesn't speak to **controller specs**.

E-mailing with @lynndylanhurley, it's clear that it's not really that hard and it could be described easily in the README, but it could be made even easier with a handful of TestHelpers along the same lines Devise and Warden provide.

I already have one simple helper written in my own project that I will contribute against this issue when I get a chance, but I'd be interested to hear what sort of things other people have seen/done for testing and what they'd want to see here.

### LINKED ISSUE #604: What's the reset password flow?
I am a little confused about how the flow goes when user want to reset their passwords. 

In my app, user will call post /password first to get the reset password email. Then he/she will click the link and it will redirect to my redirect_url with token, uid and I believe this redirect_url will lead the user to the password form. Then using that form with the token and uid, call put /password to reset the password. 

I wonder if this is the right flow. If yes, then there is one thing I feel strange. Say we have a user getting the reset password email and click the link to the form. Then he/she closes the page by accident. So he/she comes to the email and again to click the same link but it will return a 404 resource not found issue. I looked into the code and seeing that when calling get /password/edit, the controller first execute this 
`
     @resource = resource_class.reset_password_by_token({
        reset_password_token: resource_params[:reset_password_token]
      })
`

Then inside the reset_password_by_token method, it accept password and password_confirmation as parameters as well as reset_password_token. Lastly, it will update the reset_password_token which cause the email link invalid when hit it the second time. So I think when calling reset_password_by_token method in the edit action, it should also get the password and password_confirmation right? Otherwise, the link will go invalid.

### LINKED ISSUE #745: minor error in README with regard to usage alongside Devise
Hi,

I noticed the README gives the following snippet of code (https://github.com/lynndylanhurley/devise_token_auth#configinitializersdevise_token_authrb):

```
DeviseTokenAuth.setup do |config|
  # config.enable_standard_devise_support = false
end
```

This does not make sense to me. Shouldn't this be:

```
DeviseTokenAuth.setup do |config|
    config.enable_standard_devise_support = true
end
```

If this is a really a mistake I'll create a pull request but I'm not sure at this point yet.

### LINKED ISSUE #1069: Simplify the Readme.
The first sentence should be a 25-word description of WHAT THIS GEM DOES.

The second sentence may be a 25-word description of HOW IT DOES IT. The big picture.

And only then the rest of Readme (what it integrates with, the options, the settings etc.).

Ideally, it should be a website with a new page for each section.

Request for contributions goes to the bottom.

### LINKED ISSUE #1114: New Bounty: $100 for README Edits/Improvements, issue queue cleanup
Hi all,

The core team could really use some help cleaning up the README.md file!

We're offering a $100 bounty for:
- [ ] Separating the README into Wiki files, or just separate .md files
- [ ] Editing the README to some degree to ensure it's still accurate
- [ ] Going through the issue list for any README edits and making sure they get done

@lynndylanhurley , @MaicolBen and myself will decide who gets this grant, but we can use this issue as a central place for discussion of it.

We'll be funding it through our Open Collective account at https://opencollective.com/devise_token_auth

### PR DESCRIPTION
**Pull request by MaicolBen**
### Summary

The idea of this PR is cleaning the long and confusing README, and move a lot of information to a doc section. The docs can be accessed through [gitbook](https://maicolben.gitbooks.io/devise-token-auth/), you can search and see the information organized in pages there. 

Also, I moved the wiki to the docs as FAQ, so can review the doc changes through PR requests and it's in one place, so the wiki will disappear.

[Preview](https://github.com/MaicolBen/devise_token_auth/tree/refactor_readme)

### Issues resolved

Resolves #1114
Resolves #745
Resolves #604
Resolves #75
Resolves #1069

About #604, I tried to cover all the questions/doubts in the existing wiki, there is an alternative flow asked there, that #1072 will cover.
About #75, it's covered in the "Testing with Rspec" section

### Notes:

* The gitbook is pointed to my subdomain, but once this PR is merged, we'll change it to Lynn's account
* After this PR is merged, I will point the gitbook doc in https://stackoverflow.com/tags/devise-token-auth/info

### CODE REVIEW

**Comment by zachfeldman** [comment]
This is amazing @MaicolBen !

**Comment by dks17** [comment]
Is the link of demo app correct?
> For example, the demo app uses the default omniauth_prefix setting /omniauth, so the "Authorization callback URL" for github must be set to "http://devise-token-auth-demo.herokuapp.com**/omniauth**/github/callback".

The [demo app](http://devise-token-auth-demo.herokuapp.com) looks not working. Is it OK?

**Comment by MaicolBen** [comment]
@dks17 @lynndylanhurley  That's an example, isn't it? 

Also, the [Angular 2](angular2-token.herokuapp.com) demo is down, should I remove the link? Or open a new ticket for it?

**Comment by zachfeldman** [comment]
@MaicolBen I think we should merge this, then file further issues for other outstanding README problems (like possibly non-working demos). Sound good?

**Comment by MaicolBen** [comment]
Sounds good! I think we need @lynndylanhurley's approval, and we are good to go

**Comment by neroniaky** [comment]
@dks17 I updated the demo to use stackblitz: https://stackblitz.com/github/neroniaky/angular-token 
Gonna see how it works and create a PR later.

**Pull request merged**
