### PR TITLE
Fix rails 5 deprecation and devise parameter sanitization

### PR DESCRIPTION
**Pull request by djsegal**
Resolves: #504

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
hey @djsegal - do you mind rebasing against master and i can merge so long as tests are passing

**Comment by djsegal** [comment]
@booleanbetrayal:

 + @fivetwentysix's rebase looks good. one thing I noticed was that `skip_after_filter` still uses the word `filter`. do we need to change that, too?

**Comment by fivetwentysix** [comment]
@djsegal updated

**Comment by booleanbetrayal** [comment]
just merged #507. feel free to create any follow up issues as necessary, but closing this to reduce confusion.

**Pull request closed without merging**
