### PR TITLE
Use lockable devise option and unlock controller overwrite

### PR DESCRIPTION
**Pull request by genaromadrid**
- Add use of `devise :lockable` in resource model.
- Ability to overwrite UnlockController 

Sorry for the short description but i think its self explanatory.
Great gem btw
#346

### CODE REVIEW

**Comment by genaromadrid** [comment]
hey @lynndylanhurley, were you able to check this PR? What do you think? 

Cheers

**Comment by lynndylanhurley** [comment]
@genaromadrid - thx so much for this PR. I'm super busy but I'll review ASAP!

**Comment by genaromadrid** [comment]
@lynndylanhurley perfect, its really a super non-breaking change. I only changed/add a few lines and add tests. Whenever you're ready!!

**Comment by buccfer** [comment]
What is the status of this feature?

**Comment by genaromadrid** [comment]
@buccfer it's fully functional, i use it in a production service.

**Comment by buccfer** [comment]
@genaromadrid  I meant, why hasn't been merged yet?

**Comment by genaromadrid** [comment]
Well no, it still open. I think @lynndylanhurley could give you a better answer but if you can pull it down and test it, it's always good to have a second opinion .

**Comment by sumit20rai** [comment]
@lynndylanhurley Can you please review and merge this?

**Comment by sumit20rai** [comment]
@genaromadrid any idea why it is still open?

**Comment by genaromadrid** [comment]
@sumit20rai i dont know, maybe @booleanbetrayal can give us some feedback?

**Comment by fastindian84** [comment]
+1
 I also need this feature in my project. 
@lynndylanhurley  Can an you please review and merge it?

**Comment by tborisova** [comment]
+1

**Comment by genaromadrid** [comment]
@fastindian84 i'm sorry but i dont have the time right now, besides it doesn't seem that this PR is ever going to be merged... 

@lynndylanhurley, @booleanbetrayal at least 9 guys want this feature, i know you probably don't have the time to maintain this gem but **it is a great gem**. If you want help i can offer myself as a contributor/member and review some of the PRs that are pending.

Cheers

**Comment by danielneis** [comment]
+1

**Comment by danielneis** [comment]
@genaromadrid thank you for the patch! it seems really promising.
Could you please rebase you branch to the latest oficial master? =)

**Comment by v3rron** [comment]
+1 this should be definitely merged, one of the essential security features

**Comment by booleanbetrayal** [comment]
Thanks for this @genaromadrid and sorry for delay in reviewing!

**Comment by v3rron** [comment]
Sweet, thanks! Can you also please bump up Gem version number?

**Comment by booleanbetrayal** [comment]
Going through a backlog. Planning on it later today or tomorrow!

**Comment by booleanbetrayal** [comment]
Just published as 0.1.40 !

**Comment by dylanlewis89** [comment]
Thanks for this feature! Really awesome and I have a quick question.

By default, the link sent to users after their account has been locked hits Devise's `unlocks#show` [action](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/unlocks_controller.rb#L21), which fails when using Rails in API-only mode. I see that you've offered the opportunity to override this controller but I just wanted to make sure I wasn't missing some more standard way to redirect users back to a custom, client-side app URL instead of the default behavior. I'm thinking something like a `redirect_url` that can be set in the query params or a devise token auth config like `default_confirm_success_url`.

Thanks again!

**Pull request merged**
