### PR TITLE
Fix for issue #677

### PR DESCRIPTION
**Pull request by develop-test1**
Fixes duplicate confirmation e-mails.

### CODE REVIEW

**Comment by brunowego** [comment]
@develop-test1 thanks for this. I get this issue too.

**Comment by MaicolBen** [comment]
@develop-test1 I think the travis issue isn't related with this PR, can you rebase this?

**Comment by zachfeldman** [comment]
@lynndylanhurley any problems with merging this? Seems like just a simple fix to me.

**Comment by lynndylanhurley** [comment]
Thanks @develop-test1 !!

**Comment by lynndylanhurley** [comment]
Looks like this fails for users without `:confirmable`. Easy fix, working on it now

**Comment by develop-test1** [comment]
Thanks all :)

**Pull request merged**
