### PR TITLE
update/Ruby 3.x and Rails 7.0

### PR DESCRIPTION
**Pull request by jotolo**
Testing against different ruby and rails versions

Ruby:
- [x] 3.0
- [x] 3.1
- [x] 3.2

Rails: 
- [x] 7.0

#### Description
- Updating Gemfile for Rails 7.0
- Adding Rails 7 Gemfile to test matrix
- Adding exclusions for Rails 7 and Ruby versions
- Update to checkout@v3 on Github Actions
- Remove Travis configuration file
- Fixing some typos

### CODE REVIEW

**Comment by jotolo** [comment]
Hi @MaicolBen ! Thanks for supporting this gem and the work you guys have done. 
I opened this PR to update the test matrix and check against more ruby and Rails versions. 
I noticed the master branch is broken at the moment. I was wondering if there is any plan to fix it or if there is anything I can help with. I am working on a migration of an app to ruby 3.2 and I would like all the gems we use to pass with this version of Ruby.
Also, showing it is compatible using this: https://railsbump.org/ would be a very good thing to have for all people using this gem.
Please, let me know how I can help and again, thanks for the work on this library and to all maintainers.

**Comment by MaicolBen** [comment]
@jotolo I fixed the master build, can you rebase?

**Comment by jotolo** [comment]
@MaicolBen Ready to go. I included the gemfile for Rails 7.1. I am not sure if the travis config file is being used. Let me know if it is not to remove it.
Thanks for checking 🤝

**Comment by MaicolBen** [comment]
Thanks, we aren't using travis anymore

**Comment by MaicolBen** [comment]
Weird, it fails on ruby 3 now 🤔

**Comment by jotolo** [comment]
@MaicolBen I managed to update some dependencies for Rails 7 using appraisal. Once those are up to date the tests pass.
Please, check and let me know. I have also removed the travis configuration file.

**Comment by MaicolBen** [comment]
@jotolo Nice job 👏

**Pull request merged**
