### PR TITLE
Support Rails 7.0

### PR DESCRIPTION
**Pull request by enomotodev**

### CODE REVIEW

**Review by artplan1 — APPROVED** [review]

**Comment by connortorrell** [comment]
Ready to merge, I'm waiting for this change?

**Review by mbackermann — APPROVED** [review]

**Review by connortorrell — APPROVED** [review]

**Review by booleanbetrayal — APPROVED** [review]

**Comment by booleanbetrayal** [comment]
I have not had a chance to do any integration testing with this branch (looks like others may have), but I'm fine getting it into `master` for easier iteration.

**Comment by mbackermann** [comment]
There's a known issue with devise working with api only on rails 7. I reported it this week
https://github.com/heartcombo/devise/issues/5443

This bug may affect this PR.

**Comment by booleanbetrayal** [comment]
> There's a known issue with devise working with api only on rails 7. I reported it this week [heartcombo/devise#5443](https://github.com/heartcombo/devise/issues/5443)
> 
> This bug may affect this PR.

Thanks @mbackermann - Hopefully relaxing the `gemspec` constraint in `master` helps to generate incentive for people to help fix that upstream Devise issue.

**Comment by Petercopter** [comment]
Will there be a new release cut for this change, or should we be testing against master?

**Comment by booleanbetrayal** [comment]
@Petercopter - It would be nice to get some additional confirmation around Rails 7 interop before bumping gem versions, especially given the known issue with Devise. Probably prudent to let it simmer in master for a bit.

**Comment by meliborn** [comment]
it's time?

**Comment by mcelicalderon** [comment]
@mbackermann is there any update on the issue with devise?

**Pull request merged**
