### PR TITLE
Portuguese Translation

### PR DESCRIPTION
**Pull request by rmvenancio**
Portuguese (portugal) translation

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
@rmvenancio - would you mind squashing these commits into a single commit?

**Comment by rmvenancio** [comment]
@booleanbetrayal Done. Hope everything is ok now.

**Comment by booleanbetrayal** [comment]
Thanks @rmvenancio !

**Comment by rmvenancio** [comment]
You're welcome @booleanbetrayal. BR.

**Pull request merged**
