### PR TITLE
Use I18n for error messages

### PR DESCRIPTION
**Pull request by lukaselmer**

### CODE REVIEW

**Comment by felipegs** [comment]
There are anothers messages that should be placed in internationalization file:
https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/passwords_controller.rb

https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/registrations_controller.rb

https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/sessions_controller.rb

https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/token_validations_controller.rb

**Comment by lukaselmer** [comment]
Indeed, thanks for pointing that out. I'll do it.

**Comment by lynndylanhurley** [comment]
Thanks @lukaselmer! Let me know when those other files are updated and I'll merge ASAP!

**Comment by Tiagoperes** [comment]
Will the messages in the files pointed by @felipegs be transfered to the internationalization file? If not, is there another way to translate them based in the user's language?

**Comment by n5ken** [comment]
+1, I need i18n, it's great if this gem is able to support this function.

**Comment by oniofchaos** [comment]
+1 this would be very useful to have completed.

**Comment by booleanbetrayal** [comment]
Closing in favor of #283

**Pull request closed without merging**
