### PR TITLE
contemplate single table inheritance in DeviseTokenAuth::Concerns::SetUserByToken#set_user_by_token

### PR DESCRIPTION
**Pull request by maxwells**
contemplate single table inheritance in DeviseTokenAuth::Concerns::SetUserByToken#set_user_by_token

addresses https://github.com/lynndylanhurley/devise_token_auth/issues/982 for the Dockwa organization

cc @johnnagro

### CODE REVIEW

**Comment by lynndylanhurley** [comment]
Good catch @maxwells. I'll merge once we get one more approval

**Comment by zachfeldman** [comment]
This makes sense to me from reading the PR and issue. Seems that is_a is a bit less restrictive class check. I'm going to merge.

**Comment by johnnagro** [comment]
@zachfeldman @lynndylanhurley when are you folks considering another release?

**Comment by lynndylanhurley** [comment]
@johnnagro ASAP

**Pull request merged**
