### PR TITLE
Ignore 'extra' in Twitter auth response to avoid CookieOverflow. Fixes #145.

### LINKED ISSUE #145: Twitter OAuth always throughs CookieOverflow
I've tried to fix this up and a lot of what I read online suggests to either not use cookies for the session storage or to remove some attributes from the auth response from twitter which has extra parameter which seems to be too big to store.

### PR DESCRIPTION
**Pull request by tbloncar**
This addresses #145.

### CODE REVIEW

**Comment by lynndylanhurley** [comment]
Thx @tbloncar!!

**Comment by lynndylanhurley** [comment]
You're now [an official contributor](https://github.com/lynndylanhurley/devise_token_auth#callouts)!

**Comment by tbloncar** [comment]
Thanks, @lynndylanhurley.

**Comment by lynndylanhurley** [comment]
I just pushed version `0.1.32.beta7`. Please pull it down and confirm that it works ok.

**Comment by nicolas-besnard** [comment]
What does it change to remove the 'extra' parameter ?

**Comment by lynndylanhurley** [comment]
The schema description is [here](https://github.com/intridea/omniauth/wiki/Auth-Hash-Schema). I'm not sure exactly - I think it varies by provider.

**Comment by nicolas-besnard** [comment]
I'm not sure this is the right think to do. I'm using this `extra` parameters on my projects.

**Comment by tbloncar** [comment]
@nicolas-besnard Your point makes sense to me; I think the issue here is that the default behavior for Twitter auth (before this change) was a raise of `ActionDispatch::Cookies::CookieOverflow`. While this change ameliorates that issue, I see that it may result in missing some of the data you mentioned.

One alternative to this solution is making some mention of [using an alternate session store](http://stackoverflow.com/a/7117725) (like ActiveRecord store) in the README. This would be "as needed," of course. Another option might be using `except('extra')` for only the Twitter callback (for now).

**Comment by c0mrade** [comment]
Yeah I got the same `CookieOverflow` from google too, and I'm using a database as a data store. It all depends what info are you looking to get. It may or may not resolve in the issue. Yeah doesn't sound right to restrict people who want to get that extra info (I myself don't use or need it), just thinking out loud.

**Comment by nicolas-besnard** [comment]
As this is an API, we don't need Cookie or Session. I just think the
implementation of Omniauth is not valid on this gem. I'll dig this this
weekend.

**Comment by c0mrade** [comment]
Yes that was my initial thought but I had some errors and had to deliver something, so I ended up adding session middleware so the code works, thanks for reminding me I will need to remove that.

**Comment by medaglia** [comment]
I too am using omniauth_facebook and require the data passed via `extra` (age_range, gender, etc). I wasn't able to override redirect_callbacks (whereas i have no problem overriding omniauth_failure).  Does anyone have any any good suggestions? Right now I'm torn between...
1. branching omniauth_facebook to pass the data through `info` instead of `extra`
2. branching devise_token_auth to keep `extra`

**Pull request merged**
