### PR TITLE
Prevent bleeding of previous user's token with enable_standard_devise_support

### PR DESCRIPTION
**Pull request by aaronshim**
Hi! Here are some thoughts that I had on this gem from using it in my projects:

- I found a bug with the option `enable_standard_devise_support` turned on where if you log in as user 1, log in as user 2, call the REST api with user 1's token, then call the REST api with user 2's token, the very last call that is made with user 2's token will execute as if the authenticated user is user 1. I believe this happens because warden aggressively caches the currently logged-in user, and this takes precedence over a explicitly stated token/uid in the header if the `enable_standard_devise_suport` is turned on. I would propose giving precedence to an explicitly set token/uid in the header or params, even if the `enable_standard_devise_support` option is turned on.

- The SetUserByToken does not play nicely with Single Table Inheritance because of a strict class check to see if the resource obtained through authorization is the same class name as our expected resource class. I propose relaxing the constraints of this check to a `.is_a?` rather than a strict `.class ==`.

Please let me know what you think! Your feedback will be very much appreciated!

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
This seems sane @aaronshim -- but we'd need to get tests fixed and conflicts resolved. Would you mind doing that in a rebase?

**Comment by aaronshim** [comment]
Oops! I will get on it! I'm currently out of town, though, so it might be a
couple days until I can get something pushed. Sorry for the delay!


Thank you,
Aaron Shim

**Comment by zachfeldman** [comment]
Hi there @aaronshim    ,

In an effort to cleanup this project and prioritize a bit, we're marking pull requests that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this pull request. Obviously feel free to re-open it at any time if it's the right time or this was done in error! If you do, please rebase it with the latest master and explain why it's still needed.

We really appreciate your contribution, we're just trying to make this project manageable again to move it forward.

Hope all is well.

**Comment by aaronshim** [comment]
Let me think about this a bit more and re-submit a pull if I get it figured out. Thanks so much!

**Comment by zachfeldman** [comment]
Thanks @aaronshim !

**Pull request closed without merging**
