### PR TITLE
Support for devise 4.3 that is now supporting rails 5.1 

### PR DESCRIPTION
**Pull request by silviusimeria**
Issue #875

### CODE REVIEW

**Comment by edwardmp** [comment]
Was just creating something similar, thanks. @lynndylanhurley could you merge this in asap please?

**Comment by mvz** [comment]
Please consider changing the Devise dependency so that you won't have to change it when Devise 4.3.1 comes out. E.g., use `< 4.4`.

**Comment by edwardmp** [comment]
@mvz that sounds like a good idea

**Comment by silviusimeria** [comment]
@mvz @edwardmp Using `< 4.4` might have been better indeed. I doubt a new version of  Devise will be released soon, though.

**Comment by booleanbetrayal** [comment]
Just bumped this to `< 4.4` in master

**Pull request merged**
