### PR TITLE
Rubocop Fixes

### LINKED ISSUE #1124: Add Rubocop
This will improve remarkably the quality of the repo, but currently, there are 2563 issues on rubocop, so it will take a while, this can be done by parts (folders or whatever group of files).

### PR DESCRIPTION
**Pull request by dks17**
#1124
Folows the #1125 
Fixes:

### CODE REVIEW

**Comment by Evan-M** [comment]
@dks17: Thanks for this! 

Unfortunately, I had to rebase my branch against the latest HEAD of master, and I did a --force push!  (Probably should _not_ have done that, since others have access to this branch repo). I think in doing so, I've introduced some of these conflicts?

I've got a backup branch locally from before I did my rebase, so I'll try doing a force push of that back to the `add_rubocop` branch, to restore the previous state.

**Comment by dks17** [comment]
@Evan-M, I encountered only one conflict. It is OK now. I hope I did all properly.

**Comment by Evan-M** [comment]
I was actually thinking that instead of re-running the auto-gen, you would just manually remove the specific cops from the `.rubocop_todo.yml`.  However, it is curious to me that when you ran `rubocop --auto-gen-config --exclude-limit 35` the resulting `.rubocop_todo.yml` file re-enabled some of the cops that I'd fixed already...

If everyone's run of rubocop is non-deterministic, then this doesn't all quite work right?

What version of ruby are you running rubocop on?  I'm using `2.4.2p198` on MacOS `10.13.3` (High Sierra).

> I hope I did all properly.
Hey, no worries! We're figuring this out as we go, right? ¯\_(ツ)_/¯

**Comment by Evan-M** [comment]
@dks17 I'm going to go ahead and merge this into PR #1125.

We'll figure out the specific cop settings afterwards.

**Comment by dks17** [comment]
> What version of ruby are you running rubocop on? I'm using 2.4.2p198 on MacOS 10.13.3 (High Sierra).

@Evan-M, I am using `ruby 2.5.0p0 (2017-12-25 revision 61468)`. I think that is not matter in this case.

**Pull request merged**
