### PR TITLE
Support for i18n in mailers views 

### PR DESCRIPTION
**Pull request by ponyesteves**
With the english and spanish respective translations.

I've included the translation for mails subjects in the es.yml (this translation is usually included in [devise translations](https://github.com/plataformatec/devise/wiki/I18n) 'cause ir seems natural to keep al mails views translations together but i'm not sure if is a good practice. Anyway, it's only 3 lines so i've can delete them if request. 

bye

### CODE REVIEW

**Comment by ponyesteves** [comment]
HI @booleanbetrayal @lynndylanhurley , 
                                  Must I update my PR to be updated with master branch or normally you take care of that stuff. If i must, wich is the best practice to do so. Merge master into my fork master branch, resolve conflicts and push it again?

thanks,

**Comment by ValentinTrinque** [comment]
I would advise to do a rebase in order to make it cleaner.

**Comment by ponyesteves** [comment]
Thanks @ValentinTrinque for your advice

I've done the rebase and its clean for merging know.

**Comment by booleanbetrayal** [comment]
@ponyesteves  - This looks great, but I can't merge without complete translations. Could you provide Google Translate translations for all the other currently supported locales? Also, I see there's 3 commits, 1 a revert of another. Could you possible squash those in another rebase? Thanks!

**Comment by ponyesteves** [comment]
@booleanbetrayal i've fixed the commits mess, now there is only one commit with all the changes (including the translations to all supported locales). Hopefully Google have done a good job on those translations, but i wouldn't risk my neck. So i think it should be checked by someone how actually knows those languages!

**Comment by booleanbetrayal** [comment]
thanks @ponyesteves !

**Comment by ponyesteves** [comment]
You're welcome!
Glad to colaborate

**Pull request merged**
