### PR TITLE
Flag signin when user confirms email address.

### PR DESCRIPTION
**Pull request by rmvenancio**
When the user follows the confirmation link with success, he automatically sign in to the system.

The information about the number of sign in, the ip etc is not recorded in the database.
This change allows this information to be saved to the database.

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
@rmvenancio - Sorry for the delay on this. Barely managing to keep above water. Agree that this should happen as described. Could you add some specs around the sign in increment etc?

**Comment by rmvenancio** [comment]
Hi @booleanbetrayal, 

No problem. I'm also with several deliverables until the end of the year. I will create some specs but I can't promise nothing until the end of the year.

**Comment by booleanbetrayal** [comment]
@rmvenancio - We be using `sign_in` consistently across controllers (ie - SessionsController) if we decide to make this change.

**Comment by rmvenancio** [comment]
Hi @booleanbetrayal, 
Not sure if I understood your message. 

If you don't agree with that solution you can reject this PR. No problem at all. 

I think the confirmation controller have two problems: 
1st: When a user follows the confirmation link, he is automatically logged in the system but some information is not recorded (sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip and last_sign_in_ip). The call of sign_in in the confirmation controller was the (fast) way I found to solve this problem. 

2nd: The user can follow the confirmation link unlimited times and log in into the system without using a password. Possible solution was #519 in order for this solution to work, we will need to solve the 1st issue. 

Is up to you the acceptance of this PR. What you decide for me is ok. For my project I need this kind of behaviours.

**Comment by zachfeldman** [comment]
@rmvenancio nice PR.

@lynndylanhurley this doesn't seem too controversial, so I've marked it easy-to-merge.

**Pull request merged**
