### PR TITLE
[WIP] JSON API v1.0 request formatting support

### PR DESCRIPTION
**Pull request by Jeehut**
_Warning:_ This is still very much a work in progress (WIP) and this PR was only created to get early feedback on the suggested changes. Please also note that this PR has #566 as a dependency as it builds on it. So this shouldn't be merged before #566 is.

As stated in #396 with this PR I've also started working on JSON API compliant request formatting to complete the basic JSON API support. As it turns out **reading the request params** with a different format **seems to be more complicated than returning data** in a different format. At least after adding basic JSON API request deserializing and changing the test requests to send JSON API compliant request data many tests fail.

Since #566 is not getting merged or event commented on I don't feel like JSON API compliance is of any importance to the project maintainers – at least not for the moment. So I'll wait with further changes to fix the issues with the specs and instead opt for a different solution.

### CODE REVIEW

**Comment by stephanebruckert** [comment]
In your own project, how did you end up using devise_token_auth with JSONAPI? Is your branch usable now?

**Comment by Dschee** [comment]
I gave up on devise_token_auth completely since tha maintainers were not interested in this feature / due to inactivity. I‘ve implemented this feature manually ans went for json_apr_resources instead which was flexible enough.

**Comment by stephanebruckert** [comment]
I'm now using your branch directly and it works perfectly. Just what I needed. Thank you!

    gem 'devise_token_auth', :git => "git://github.com/Dschee/devise_token_auth.git", ref => "9a04e9caf9f44bb84d79b03b4c288750d152b1ea"

Would you consider forking the current `devise_token_auth` into a kind of `devise_token_auth_jsonapi` of your own? You could merge conflicts and still retrieve updates (if any). I think many people would need this, particularly those who work with Ember.

**Comment by Dschee** [comment]
@stephanebruckert As I have already said, I've given up on devise_token_auth. Why don't you do it yourself though? Just fork my fork. I'd be happy to see my hard work not being wasted and reused by a new project. 👍

**Comment by stephanebruckert** [comment]
Will do unless @lynndylanhurley would like to throw another eye on this PR? :pray:

**Comment by Dschee** [comment]
That was a good joke. 😂

**Comment by stephanebruckert** [comment]
Perhaps @booleanbetrayal could have a look?

**Comment by zachfeldman** [comment]
Hi there @Dschee    ,

In an effort to cleanup this project and prioritize a bit, we're marking pull requests that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this pull request. Obviously feel free to re-open it at any time if it's the right time or this was done in error! If you do, please rebase it with the latest master and explain why it's still needed.

We really appreciate your contribution, we're just trying to make this project manageable again to move it forward.

Hope all is well.

**Comment by lynndylanhurley** [comment]
@Dschee @stephanebruckert sorry for the delay. We're reviewing all of the open PRs now. @Dschee noted in #396 that he would like us to review this feature.

Several PRs have been merged since this was created, and now it looks like there are several conflicts. Do either of you have time to resolve the merge conflicts with this branch?

**Comment by stephanebruckert** [comment]
@lynndylanhurley thanks for the comeback! Unfortunately I won't have time to work on this anytime soon

**Pull request closed without merging**
