### PR TITLE
Old password check before password update

### PR DESCRIPTION
**Pull request by jakubrohleder**
I've added extra config param `check_current_password_before_update` with possible values of `:attributes` or `:password` and default value of `false`. 

If **`config.check_current_password_before_update`** is set to `:attributes` the **`current_password`** param is checked before any update, if it is set to `:password` the **`current_password`** param is checked only if the request updates user password.

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
LGTM!

**Comment by sebfie** [comment]
There is an issue with this pull request. We can use current_password to check before to update, but not after a request of password reset.

So, here is my workflow : 
- I ask password reset
- I fill password and password_confirmation
- It asks me the current_password

**Comment by jakubrohleder** [comment]
@sebfie Sorry for the late response, but I was on holiday. I'll look at this issue tonight / tomorrow and hopefully fix all the bugs.

**Comment by sebfie** [comment]
Perfect! Thx a lot

**Comment by jakubrohleder** [comment]
@sebfie I made a quick fix under [my fork](https://github.com/jakubrohtleder/devise_token_auth/tree/feature/password-check-before-update). It is not tested yet, but you can try if it works for you, I'll make a PR after preparing some decent tests.

**Comment by jakubrohleder** [comment]
@sebfie I just made a PR fixing this bug, sorry for a long time waiting.

**Comment by sebfie** [comment]
Thx

**Pull request merged**
