### PR TITLE
Reset password token test fix

### PR DESCRIPTION
**Pull request by dks17**
No need reload resource after update.

### CODE REVIEW

**Comment by zachfeldman** [comment]
@dks17 this seems like a really small change - can you explain its impact?

**Comment by dks17** [comment]
@zachfeldman It impacts test performance.

**Comment by zachfeldman** [comment]
Sure! If @MaicolBen or @lynndylanhurley approve of this change I'm down to merge then.

**Comment by MaicolBen** [comment]
For some reason was added in test, can you [squash](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) the commits?

**Comment by zachfeldman** [comment]
@MaicolBen for future reference we can actually auto-squash when we merge?

**Comment by zachfeldman** [comment]
https://github.com/blog/2141-squash-your-commits

**Comment by MaicolBen** [comment]
Yeah, you will lose the merge commit but it works

**Pull request closed without merging**
