### PR TITLE
confirmation should redirect to default_confirm_success_url by default

### PR DESCRIPTION
**Pull request by maysam**
#1084

### CODE REVIEW

**Comment by dks17** [comment]
It needs some tests covering the case (then `redirect_url` is absent).
Is controller suitable place to put your code? What if I need to get `redirect_url` in other controller of an application?

**Comment by maysam** [comment]
this is already following the pattern in [registrations_controller.rb#L20-L23](https://github.com/maysam/devise_token_auth/blob/12c87ebbcab2f94c7e8fb7198a48cfadd6c8ca40/app/controllers/devise_token_auth/registrations_controller.rb#L20-L23)

**Comment by dks17** [comment]
@maysam you are right.
I think that will be better to put your code and you the pattern in one place.
And anyway tests are needed.
I think.

**Comment by MaicolBen** [comment]
Merging as the author didn't show up anymore and it isn't mandatory in this case the tests as it's pretty simple.

**Pull request merged**
