### PR TITLE
Implement hook methods for customized json rendering

### PR DESCRIPTION
**Pull request by neutronz**
I've added hook methods in the devise token auth controllers that can be overridden without having to override the entire controller just to get custom json rendering abilities.

### CODE REVIEW

**Comment by leonhall** [comment]
+1 :+1:

**Comment by akshah123** [comment]
:+1:

**Comment by lynndylanhurley** [comment]
This looks great, thanks @neutronz!!

**Comment by neutronz** [comment]
You got it @lynndylanhurley thanks for your work.

**Pull request merged**
